### ISSUE TITLE
Need to check firewalls if they have logging enabled

### ISSUE THREAD

**Issue by sukchomb** [inspec/inspec-gcp#223]
Need this to be testable in Inspec.

## Context
Being able to evidence that logging is enabled will further strengthen platform's security posture.

## Possible Implementation
The inspec singular resource https://www.inspec.io/docs/reference/resources/google_compute_firewall/
does not at the current time tests whether logging is enabled.

the API in https://cloud.google.com/compute/docs/reference/rest/v1/firewalls exposes section:

"logConfig": {
    "enable": boolean
  },

**Comment by slevenick** [comment]
This *might* be testable via InSpec currently. If the field is present on the response it should be testable via the resource though it may not be documented.

Try doing something like:
```
describe google_compute_firewall(your-identifiers) do
  its('log_config.enable') { should be true }
end
```

My goal for the next couple months is to move these handwritten resources to be generated via a code generator which will ensure they have up-to-date documentation

**Comment by mattbowes** [comment]
We are interested in being able to monitor this too. 
 
`its('log_config.enable') { should be true }`

Does not work, give an undefined method error 

`  undefined method 'log_config' for Firewall Rule<removed>:#<Class:0x00005645988c7d30>`

**Comment by sukchomb** [comment]
I get the same undefined method error as well.

undefined method `log_config' for Firewall Rule<removed>:#<Class:0x000000000d479d68>

**Comment by slevenick** [comment]
That method is likely not defined due to the API not returning the `logConfig` block, which means that logging is not turned on.

If the `logConfig` block is not specified you will need to check if the InSpec resource has the `log_config` method defined prior to using `its('log_config.enable)`. I've had luck in the past using something like:
```
firewall = google_compute_firewall(identifiers)
if firewall.respond_to?('log_config') do
  your normal test here
else
  fail or skip the test here, method not defined
end
```

I'm close to being able to move these resources over to being generated, which should make this issue obsolete.

**Comment by jvogt** [comment]
It looks like earlier versions of google-api-client gem used by inspec-gcp didn't support log_config.

I was able to replicate this with chefdk 4.2.0, but after upgrading to chefdk 4.6.35 (which comes with the latest google-api-client), inspec was successful in parsing this attribute.

**Comment by jvogt** [comment]
Also validated latest version of inspec from downloads.chef.io contains the most recent google-api-client and should also work (without requiring chefdk)

**Comment by lhasadreams** [comment]
Thanks @jvogt 
I am seeing the same with InSpec 4.18.39
So all good - this can be closed

**Comment by lhasadreams** [comment]
Works on 4.18.51 for me as well.

**Comment by slevenick** [comment]
Good to hear!
